using System.Net;
using System.Net.NetworkInformation;
using System.Net.Sockets;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

using LunaRelay.Setup;

string root = Path.GetFullPath(args.FirstOrDefault() ?? Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
string secretsPath = Path.Combine(root, "secrets.h");
string privateConfigPath = Path.Combine(root, "main", "private_config.h");
if (!File.Exists(secretsPath) || !File.Exists(privateConfigPath))
{
    throw new InvalidOperationException("Run setup with the repository root path.");
}

Dictionary<string, string> values = ParseValues(File.ReadAllText(secretsPath));
foreach ((string key, string value) in ParseValues(File.ReadAllText(privateConfigPath)))
{
    values[key] = value;
}

string Required(string name) => values.TryGetValue(name, out string? value) && value.Length != 0
    ? value
    : throw new InvalidOperationException($"Missing local firmware setting {name}.");

IPAddress address = FindLanAddress();
string ttsEndpoint = Required("AZURE_TTS_ENDPOINT");
string speechRegion = new Uri(ttsEndpoint).Host.Split('.')[0];
string token = Base64Url(RandomNumberGenerator.GetBytes(32));
string certificatePassword = Base64Url(RandomNumberGenerator.GetBytes(24));

string relayDirectory = Path.Combine(root, "relay");
string certificateDirectory = Path.Combine(relayDirectory, "certs");
string firmwareCertificateDirectory = Path.Combine(root, "main", "certs");
Directory.CreateDirectory(certificateDirectory);
Directory.CreateDirectory(firmwareCertificateDirectory);

using RSA rsa = RSA.Create(2048);
var request = new CertificateRequest(
    "CN=Luna Local Relay", rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
request.CertificateExtensions.Add(new X509BasicConstraintsExtension(false, false, 0, true));
request.CertificateExtensions.Add(new X509KeyUsageExtension(
    X509KeyUsageFlags.DigitalSignature | X509KeyUsageFlags.KeyEncipherment, true));
request.CertificateExtensions.Add(new X509EnhancedKeyUsageExtension(
    new OidCollection { new("1.3.6.1.5.5.7.3.1") }, true));
var san = new SubjectAlternativeNameBuilder();
san.AddIpAddress(address);
san.AddDnsName("localhost");
san.AddDnsName(Environment.MachineName);
request.CertificateExtensions.Add(san.Build());
using X509Certificate2 certificate = request.CreateSelfSigned(
    DateTimeOffset.UtcNow.AddDays(-1), DateTimeOffset.UtcNow.AddYears(2));

File.WriteAllBytes(Path.Combine(certificateDirectory, "relay.pfx"),
    certificate.Export(X509ContentType.Pfx, certificatePassword));
string certificatePem = PemEncoding.WriteString("CERTIFICATE", certificate.RawData);
File.WriteAllText(Path.Combine(firmwareCertificateDirectory, "relay_ca.pem"), certificatePem);

var settings = new
{
    Relay = new
    {
        ListenPort = 7443,
        DeviceToken = token,
        CertificatePath = "certs/relay.pfx",
        CertificatePassword = certificatePassword,
    },
    AzureSpeech = new
    {
        Key = Required("AZURE_SPEECH_KEY"),
        Region = speechRegion,
        Language = values.GetValueOrDefault("SPEECH_LANGUAGE", "en-IN"),
        Voice = values.GetValueOrDefault("TTS_VOICE_ENGLISH", "en-IN-NeerjaNeural"),
    },
    AzureOpenAI = new
    {
        Endpoint = Required("AZURE_AI_ENDPOINT"),
        ApiKey = Required("AZURE_AI_API_KEY"),
        Model = Required("AZURE_AI_MODEL"),
    },
};
File.WriteAllText(Path.Combine(relayDirectory, "appsettings.Local.json"),
    JsonSerializer.Serialize(settings, new JsonSerializerOptions { WriteIndented = true }));

string relayUri = $"wss://{address}:7443/voice";
File.WriteAllText(Path.Combine(root, "main", "relay_config.h"), $$"""
    #pragma once

    // Generated by LunaRelay.Setup. This file contains a revocable local device token.
    #define LUNA_RELAY_URI "{{relayUri}}"
    #define LUNA_RELAY_DEVICE_TOKEN "{{token}}"
    """);

Console.WriteLine("Generated local relay TLS, ignored settings, and firmware relay configuration.");

static Dictionary<string, string> ParseValues(string source)
{
    var values = new Dictionary<string, string>(StringComparer.Ordinal);
    const string quoted = "\"(?<value>(?:\\\\.|[^\"])*)\"";
    foreach (Match match in Regex.Matches(source,
        @"#define\s+(?<name>[A-Z][A-Z0-9_]*)\s+" + quoted))
    {
        values[match.Groups["name"].Value] = Unescape(match.Groups["value"].Value);
    }
    foreach (Match match in Regex.Matches(source,
        @"(?:static\s+)?(?:const\s+)?char\s*\*\s*(?<name>[A-Z][A-Z0-9_]*)\s*=\s*" + quoted))
    {
        values[match.Groups["name"].Value] = Unescape(match.Groups["value"].Value);
    }
    return values;
}

static string Unescape(string value) =>
    JsonSerializer.Deserialize<string>($"\"{value}\"") ?? string.Empty;

static IPAddress FindLanAddress()
{
    var candidates = new List<LanAddressCandidate>();
    foreach (NetworkInterface network in NetworkInterface.GetAllNetworkInterfaces())
    {
        foreach (UnicastIPAddressInformation address in network.GetIPProperties().UnicastAddresses)
        {
            candidates.Add(new LanAddressCandidate(
                network.OperationalStatus == OperationalStatus.Up &&
                    network.NetworkInterfaceType is not NetworkInterfaceType.Loopback and not NetworkInterfaceType.Tunnel,
                network.NetworkInterfaceType == NetworkInterfaceType.Wireless80211,
                address.Address));
        }
    }
    return LanAddressSelector.Select(candidates);
}

static string Base64Url(byte[] bytes) =>
    Convert.ToBase64String(bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_');
