param(
    [string]$ResourceGroup = 'luna-relay-rg',
    [string]$Location = 'eastus',
    [string]$AppName = 'luna-relay',
    [string]$EnvironmentName = 'luna-relay-env'
)

$ErrorActionPreference = 'Stop'

function Invoke-Az {
    param([Parameter(ValueFromRemainingArguments = $true)][string[]]$Arguments)

    & az @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Azure CLI command failed: az $($Arguments -join ' ')"
    }
}

$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$settingsPath = Join-Path $root 'relay\appsettings.Local.json'
$firmwareConfigPath = Join-Path $root 'main\relay_config.h'
$statePath = Join-Path $root 'relay\.cloud-deployment.json'

if (-not (Test-Path -LiteralPath $settingsPath) -or -not (Test-Path -LiteralPath $firmwareConfigPath)) {
    throw 'Generate ignored local relay settings before deployment.'
}
if (Test-Path -LiteralPath $statePath) {
    throw 'Existing cloud deployment state found. Update the existing app instead of creating a second charged relay.'
}

$settings = Get-Content -Raw -LiteralPath $settingsPath | ConvertFrom-Json
$tokenMatch = [regex]::Match(
    (Get-Content -Raw -LiteralPath $firmwareConfigPath),
    '(?m)^\s*#define\s+LUNA_RELAY_DEVICE_TOKEN\s+"(?<token>[^"]+)"\s*$')
if (-not $tokenMatch.Success) {
    throw 'Could not read the generated relay device token.'
}

Invoke-Az account show --only-show-errors | Out-Null
Invoke-Az extension add --name containerapp --upgrade --yes --only-show-errors | Out-Null
Invoke-Az provider register --namespace Microsoft.App --wait --only-show-errors | Out-Null
Invoke-Az provider register --namespace Microsoft.ContainerRegistry --wait --only-show-errors | Out-Null

$suffix = [guid]::NewGuid().ToString('N').Substring(0, 10)
$registryName = "lunarelay$suffix"
$identityName = "$AppName-pull"

Invoke-Az group create --name $ResourceGroup --location $Location --only-show-errors | Out-Null
Invoke-Az acr create --name $registryName --resource-group $ResourceGroup --sku Basic --only-show-errors | Out-Null
$identity = Invoke-Az identity create --name $identityName --resource-group $ResourceGroup --location $Location --only-show-errors | ConvertFrom-Json
$registryId = Invoke-Az acr show --name $registryName --resource-group $ResourceGroup --query id --output tsv --only-show-errors
$registryLoginServer = Invoke-Az acr show --name $registryName --resource-group $ResourceGroup --query loginServer --output tsv --only-show-errors

Invoke-Az role assignment create --assignee-object-id $identity.principalId --assignee-principal-type ServicePrincipal `
    --role AcrPull --scope $registryId --only-show-errors | Out-Null

Invoke-Az containerapp env create --name $EnvironmentName --resource-group $ResourceGroup --location $Location --only-show-errors | Out-Null

$imageTag = 'luna-relay:v1'
$image = "$registryLoginServer/$imageTag"
Invoke-Az acr build --registry $registryName --image $imageTag --file relay/Dockerfile . --only-show-errors

$secrets = @(
    "relay-device-token=$($settings.Relay.DeviceToken)",
    "speech-key=$($settings.AzureSpeech.Key)",
    "openai-key=$($settings.AzureOpenAI.ApiKey)"
)
$environment = @(
    'ASPNETCORE_ENVIRONMENT=Production',
    'Relay__ListenPort=8080',
    'Relay__UseTls=false',
    'Relay__DeviceToken=secretref:relay-device-token',
    'AzureSpeech__Key=secretref:speech-key',
    "AzureSpeech__Region=$($settings.AzureSpeech.Region)",
    "AzureSpeech__Language=$($settings.AzureSpeech.Language)",
    "AzureSpeech__Voice=$($settings.AzureSpeech.Voice)",
    "AzureOpenAI__Endpoint=$($settings.AzureOpenAI.Endpoint)",
    'AzureOpenAI__ApiKey=secretref:openai-key',
    "AzureOpenAI__Model=$($settings.AzureOpenAI.Model)"
)

Invoke-Az containerapp create --name $AppName --resource-group $ResourceGroup --environment $EnvironmentName `
    --image $image --ingress external --target-port 8080 --transport auto --min-replicas 1 --max-replicas 1 `
    --user-assigned $identity.id --registry-server $registryLoginServer --registry-identity $identity.id `
    --secrets @secrets --env-vars @environment --only-show-errors | Out-Null

$fqdn = Invoke-Az containerapp show --name $AppName --resource-group $ResourceGroup `
    --query properties.configuration.ingress.fqdn --output tsv --only-show-errors
if ([string]::IsNullOrWhiteSpace($fqdn)) {
    throw 'Azure Container Apps did not return a public FQDN.'
}

$relayUri = "wss://$fqdn/voice"
$firmwareHeader = @"
#pragma once

// Generated by the cloud deployment script. This file is ignored because it contains a revocable device token.
#define LUNA_RELAY_URI "$relayUri"
#define LUNA_RELAY_DEVICE_TOKEN "$($tokenMatch.Groups['token'].Value)"
#define LUNA_RELAY_USE_PUBLIC_CA 1
"@
[IO.File]::WriteAllText($firmwareConfigPath, $firmwareHeader, [Text.UTF8Encoding]::new($false))

$state = [ordered]@{
    ResourceGroup = $ResourceGroup
    Location = $Location
    EnvironmentName = $EnvironmentName
    AppName = $AppName
    RegistryName = $registryName
    IdentityName = $identityName
    Fqdn = $fqdn
    RelayUri = $relayUri
}
[IO.File]::WriteAllText($statePath, ($state | ConvertTo-Json), [Text.UTF8Encoding]::new($false))

Write-Host "Cloud relay deployed. Firmware configuration now targets $relayUri"
